#!/bin/bash

#Activation des quotas natifs ext4

#Probleme pour démonter /home => lancer le script depuis le mode recovery (root)

REP_QUOTAS="/home"
#-r desactive les caracteres d affichage sinon pb

PARTITION=$(lsblk -r | grep "$REP_QUOTAS" | awk '{print $1}')

NEW_PARTITION=$(fdisk -l | grep "$PARTITION" | awk '{print $1}')

apt -y install quota quotatool

#Enable Quota feature
df -h REP_QUOTAS

echo $NEW_PARTITION
# set quota feature and re-mount

umount REP_QUOTAS
tune2fs -O quota $NEW_PARTITION
mount $NEW_PARTITION $REP_QUOTAS
tune2fs -l $NEW_PARTITION | grep -i quota

